Create a `<TokenContext/>`  for storing token state with its setter and handleSubmit
selsa-inube/isetting pull request #572
Opened 2024-01-30 03:51 UTC by cmarin001

This pull request introduces the creation of a `<TokenContext/>` within our application. The purpose of this new context is to efficiently manage the state of various tokens along with their corresponding setter functions and to handle submission events. This implementation aims to streamline state management and enhance the overall functionality of our app's token-related features

2024-02-01 17:22 UTC, carin91 requested changes

2024-02-01 17:22 UTC, carin91 commented on src/routes/people.tsx
> +    <TokenProvider>
Are you sure that any other component will not need this context?, i think so, however, confirm it please.

2024-02-01 17:22 UTC, carin91 commented on src/context/TokenContext/index.tsx
> +export { TokenContext, TokenProvider };
I would create a types.ts file for at least defining the handleSubmit props interface.

2024-02-01 17:22 UTC, carin91 commented on src/pages/people/outlets/lines/interface.tsx
> +  handleSubmit: (
Does the strokes interface need to import handleSubmit. I guess that you need it to pass as prop to its forms, however, the forms can import it directly from the context, doesn't it? This applies to every form (text, surface, stroke).

2024-02-01 19:48 UTC, cmarin001 commented on src/App.tsx
> +import AppContextProvider from "./context/AppContext";
solved

2024-02-01 21:26 UTC, cmarin001 commented on src/pages/people/outlets/lines/form/RenderLinesContentForm/index.tsx
> +  handleSubmit: (
solved

2024-02-01 21:30 UTC, cmarin001 commented on src/routes/people.tsx
> +    <TokenProvider>
Currently, only people need this to visualize the changes. If, in the future, others require it, adjustments will be made to accommodate that need

2024-02-01 21:31 UTC, cmarin001 commented on src/context/TokenContext/index.tsx
> +export { TokenContext, TokenProvider };
solved

2024-02-01 21:35 UTC, cmarin001 commented on src/pages/people/outlets/lines/interface.tsx
> +  handleSubmit: (
solved

2024-02-01 22:22 UTC, cmarin001 commented on src/context/TokenContext/index.tsx
> +  token: presente,
solved

2024-02-01 22:22 UTC, cmarin001 commented on src/context/TokenContext/index.tsx
> +  const [token, setToken] = useState(presente);
solved

2024-02-01 22:22 UTC, cmarin001 commented on src/context/TokenContext/index.tsx
> +      setToken(updatedToken);
solved

2024-02-02 08:49 UTC, carin91 commented on src/pages/people/outlets/lines/interface.tsx
> +  handleSubmit: (
Pending:
As you can see in the example below you could useContext in the children which need to read it.

https://www.w3schools.com/react/react_usecontext.asp
![image](https://github.com/selsa-inube/linpar/assets/123512032/2466394d-90c1-4174-bda6-be627ff9fd09)
In this case the handleSubmit and the token are required only on the forms. You read it in there to create the theme context and also you PUT the token with the handleSubmit, you are assigning an unnecessary responsibility to the  components for the tabs. I propose changes as presented below.

![image](https://github.com/selsa-inube/linpar/assets/123512032/24b0a8df-44a5-47b2-a02a-d350c93904cc)
![image](https://github.com/selsa-inube/linpar/assets/123512032/8e782d3d-4364-45be-8402-f7422785efbe)
![image](https://github.com/selsa-inube/linpar/assets/123512032/bbc741e4-5c08-4c78-9529-8f77539b8782)

And... import the handleSubmit, token, and IhandleSubmitProps into the RenderSurfaceContentForm and the other forms.

2024-02-02 08:50 UTC, carin91 commented on src/pages/people/outlets/lines/interface.tsx
> +  handleSubmit: (
Pending:
As you can see in the example below you could useContext in the children which need to read it.

https://www.w3schools.com/react/react_usecontext.asp
![image](https://github.com/selsa-inube/linpar/assets/123512032/2466394d-90c1-4174-bda6-be627ff9fd09)
In this case the handleSubmit and the token are required only on the forms. You read it in there to create the theme context and also you PUT the token with the handleSubmit, you are assigning an unnecessary responsibility to the  components for the tabs. I propose changes as presented below.

![image](https://github.com/selsa-inube/linpar/assets/123512032/24b0a8df-44a5-47b2-a02a-d350c93904cc)
![image](https://github.com/selsa-inube/linpar/assets/123512032/8e782d3d-4364-45be-8402-f7422785efbe)
![image](https://github.com/selsa-inube/linpar/assets/123512032/bbc741e4-5c08-4c78-9529-8f77539b8782)

And... import the handleSubmit, token, and IhandleSubmitProps into the RenderSurfaceContentForm and the other forms.

2024-02-02 10:13 UTC, carin91 requested changes

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/lines/index.tsx
> +  const { token, handleSubmit } = useContext(TokenContext);
The lines index and interface do not use this information, the useContext should be used someplace else.

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/lines/interface.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
The Strokes / interface does not use this information, the IHandleSubmitProps should be used someplace else (in the forms).

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/palette/Palette.stories.tsx
> +import { TokenContext } from "@src/context/TokenContext";
i don't get it. Why the palette.stories needs the context? i supposed that the storybook was not design for that. It means that you need to pass the database information? Are you sure of it?

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/palette/index.tsx
> +import { useContext, useEffect, useState } from "react";
palette / index does not need the tokens information for anything. Place the useContext in the forms

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/surfaces/Surfaces.stories.tsx
> +import { TokenContext } from "@src/context/TokenContext";
These lines need to be reevaluated based on the revision of the storybook use.

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
The forms and its children are the components which need to know about the handleSubmit and the tokens, so, the useContext must be placed here and the children get this information through props or the themeProvider.

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/surfaces/index.tsx
> +import { useContext, useState } from "react";
The surface / index does not need the tokens information for anything. Place the useContext in the form

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/surfaces/interface.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
The Surface/ interface does not use this information, the IHandleSubmitProps should be used someplace else (in the forms).

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/texts/Texts.stories.tsx
> +import { TokenContext } from "@src/context/TokenContext";
These lines need to be reevaluated based on the revision of the storybook use.

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
The forms and its children are the components which need to know about the handleSubmit and the tokens, so, the useContext must be placed here and the children get this information through props or the themeProvider.

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/texts/index.tsx
> +import { useContext, useState } from "react";
The Text/ index does not need the tokens information for anything. Place the useContext in the form

2024-02-02 10:13 UTC, carin91 commented on src/pages/people/outlets/texts/interface.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
The Text/ interface does not use this information, the IHandleSubmitProps should be used someplace else (in the forms).

2024-02-02 10:15 UTC, carin91 commented on src/routes/people.tsx
> +    <TokenProvider>
As related in another comment, i think this is the only correct place for the tokenProvider. Why do you change it? Do you think that you will need the tokens outside people?

2024-02-02 22:58 UTC, cmarin001 commented on src/App.tsx
> +      <TokenProvider>
solved

2024-02-05 19:21 UTC, cmarin001 commented on src/pages/people/outlets/lines/interface.tsx
> +  handleSubmit: (
solved

2024-02-05 19:21 UTC, cmarin001 commented on src/pages/people/outlets/lines/index.tsx
> +  const { token, handleSubmit } = useContext(TokenContext);
solved

2024-02-05 19:22 UTC, cmarin001 commented on src/pages/people/outlets/lines/interface.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
solved

2024-02-05 19:28 UTC, cmarin001 commented on src/pages/people/outlets/palette/index.tsx
> +import { useContext, useEffect, useState } from "react";
solved

2024-02-05 19:28 UTC, cmarin001 commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
solved

2024-02-05 19:28 UTC, cmarin001 commented on src/pages/people/outlets/surfaces/index.tsx
> +import { useContext, useState } from "react";
solved

2024-02-05 19:28 UTC, cmarin001 commented on src/pages/people/outlets/surfaces/interface.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
solved

2024-02-05 19:28 UTC, cmarin001 commented on src/pages/people/outlets/texts/form/RenderTextContentForm/index.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
solved

2024-02-05 19:29 UTC, cmarin001 commented on src/pages/people/outlets/texts/interface.tsx
> +import { IHandleSubmitProps } from "@src/context/TokenContext/types";
solved

2024-02-06 11:34 UTC, carin91 approved these changes

2024-02-06 12:41 UTC, carin91 commented on src/context/TokenContext/index.tsx
> +    case actionTypes.SET_TOKEN:
This action is not in use, i guess this is for future implementation, i would evaluate to delete it.

2024-02-06 18:05 UTC, merged

2024-02-06 18:06 UTC, cmarin001 commented on src/context/TokenContext/index.tsx
> +    case actionTypes.SET_TOKEN:
we keep it for future implementation