Mock the process of requesting a backend service for representable clients
selsa-inube/isetting pull request #573
Opened 2024-01-30 08:56 UTC by carin91

Several changes:
1) I deleted the .fetch in CheckingCredentials and Clients
2) I strongly changed context including clients and a handler for the reducer, i also included the reducer and so on.
3) I included the useAuth0 hook into the context to read the user information.
4) i imported the clients mock into the context to asign this property to user context

to test functionality: http://localhost:3000/login/11/checking-credentials
This PR also included SET-652: Allow the app to always know the client that the user is representing

2024-02-01 14:55 UTC, LinconOssa requested changes
on cell phone it is not looking good
![image](https://github.com/selsa-inube/linpar/assets/103295353/fb3886cf-1730-43f9-8c27-6e0140a8b3e7)
look at the model that is in figma
![image](https://github.com/selsa-inube/linpar/assets/103295353/2af3cd3a-a302-44af-9692-565dc1425933)

2024-02-01 14:57 UTC, LinconOssa commented on src/mocks/login/clients.mock.tsx
> +  // },
I suggest deleting these comments since it is not being used

2024-02-01 14:57 UTC, LinconOssa commented on src/mocks/login/clients.mock.tsx
> +  // },
I suggest deleting these comments since it is not being used

2024-02-02 12:03 UTC, carin91 commented on src/mocks/login/clients.mock.tsx
> +  // },
not attended. In the case that it will be necessary for future mocking it will be needed.

2024-02-02 12:03 UTC, carin91 commented on src/mocks/login/clients.mock.tsx
> +  // },
not attended. In the case that it will be necessary for future mocking it will be needed

2024-02-02 22:05 UTC, cmarin001 reviewed
When we select the logout option and attempt to log in again, it automatically redirects to the <Home/> page by default, without requesting any input from the user

![image](https://github.com/selsa-inube/linpar/assets/45011420/cca3e937-dcc9-4c5c-96ba-1cae7cd19762)

2024-02-03 02:55 UTC, carin91 commented
Not attended the issue defined by @cmarin001.

As you can see in your page, you are in linpar.vercel.app/, it means, a version of the app which has not the enhancement. You will notice the correct behavior when we could merge this branch into main.

I considered that this behavior is an issue (a different one), and we should avoid reaching the linpar.vercel.app page.

2024-02-06 16:29 UTC, LinconOssa reviewed
The storybook is not working in Clients or in loading-app:
![image](https://github.com/selsa-inube/isetting/assets/103295353/1e238631-99f7-44f1-a918-f80e01493dc4)
![image](https://github.com/selsa-inube/isetting/assets/103295353/fddb289c-1b1c-4695-b206-914fdce41db2)

2024-02-06 16:40 UTC, LinconOssa approved these changes
It meets the requirements but there are some pending that will be carried out on other cards

2024-02-06 16:53 UTC, cmarin001 approved these changes
meet the requirements

2024-02-06 16:54 UTC, merged