Update <Palette/> according to the figma designLo/id653/according to the figma design
selsa-inube/isetting pull request #575
Opened 2024-01-30 22:19 UTC by LinconOssa

The palette change that was in figma is made and the hover is added so that the icon appears

2024-01-31 11:41 UTC, carin91 requested changes

2024-01-31 11:41 UTC, carin91 commented on src/components/cards/TokenColorCard/index.tsx
> +  const handleMouseEnter = () => {
Is it necessary? if you are using just the SetIsHovered why do you need to create an additional function.

2024-01-31 11:41 UTC, carin91 commented on src/components/cards/TokenColorCard/index.tsx
> +  const handleMouseLeave = () => {
Is it necessary? if you are using just the SetIsHovered why do you need to create an additional function.

2024-01-31 11:41 UTC, carin91 commented on src/components/cards/TokenColorCard/index.tsx
> +  const [isHovered, setIsHovered] = useState(false);
Why do you need this state? Is it not enough with the css pseudoclass?

2024-01-31 11:41 UTC, carin91 commented on src/components/cards/TokenColorCard/index.tsx
>    const [isActive, setIsActive] = useState(false);
I should consider the type param to control the Icon. You should verify the conditions required all over the app.

As an example you could see the undesired behavior of the tokenColor in Surface, as presented bellow.

![image](https://github.com/selsa-inube/linpar/assets/123512032/af363a3b-c53a-4f26-940d-7507a54e1468)

Is the icon in hovering needed in this situation?
![image](https://github.com/selsa-inube/linpar/assets/123512032/19a27463-d557-474e-9998-8c30781dbd09)

2024-01-31 11:41 UTC, carin91 commented on src/components/cards/TokenColorCard/index.tsx
> +        {isHovered && (
The Icon should be included inside the tokenDescription conditional rendering in line 183 to guarantee that it does not exist in the type  tokenPicker. 

![image](https://github.com/selsa-inube/linpar/assets/123512032/7fa90d13-3b27-4165-87a8-20e6159c1733)

![image](https://github.com/selsa-inube/linpar/assets/123512032/67967322-c692-4269-99f5-9e9107e44344)

Add to it, notice the "auto" label in the gap between the icon and the text, you should guarantee this condition.
![image](https://github.com/selsa-inube/linpar/assets/123512032/9d34b61b-d894-4f14-ad79-dafbbb85f02f)

2024-01-31 11:41 UTC, carin91 commented on src/components/cards/TokenColorCard/styles.ts
> +      : smallScreen
It is recommended to not nest ternary operators. Refactor this. Why do you need the "unset"?

2024-01-31 11:41 UTC, carin91 commented on src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
> +function RenderContentFormNeutralPalette(
Most of this functionality is already implemented, the tokenColorCard includes a component named RenderCategoryGrid, which had an unappropriated mirror on the palette component.

In this code you are duplicating the renderCategoryGrid twice, one for the Neutral grid and the second for the RenderContentFormPalette.
This is too much code duplicated and too much code to maintain. 

I recommend importing the RenderCategoryGrid defined in the tokenColorCard to be used in these forms.

Actually,  evaluate to create a new directory as a new component for the renderCategoryGrid (it will need its storybook too). You should be very careful with the main updating, i strongly recommend to make this change in a new brand/ as a new Jira card.

2024-01-31 11:41 UTC, carin91 commented on src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
> +import { useState } from "react";
This is a new component, for instance, it needs a new storybook file, you should create the storybook file and verify its correct behavior.

2024-02-01 20:50 UTC, LinconOssa commented on src/components/cards/TokenColorCard/index.tsx
> -import { Stack, Text, useMediaQuery, Grid, inube } from "@inube/design-system";
I agree, you can still make the corresponding revision and when it is accepted, update with the new changes

2024-02-01 20:50 UTC, LinconOssa commented on src/components/cards/TokenColorCard/index.tsx
> +  const handleMouseLeave = () => {
This method was eliminated to do it in another way than already shown in the previous image

2024-02-01 20:50 UTC, LinconOssa commented on src/components/cards/TokenColorCard/index.tsx
> +  const [isHovered, setIsHovered] = useState(false);
This method was eliminated to do it in another way than already shown in the previous image

2024-02-01 23:35 UTC, LinconOssa commented on src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
> +function RenderContentFormNeutralPalette(
They are different in the way the containers are rendered and although you are aware that if a refactor is required for the repetitive part that will be something that will be reviewed and corrected on the card (SET671) that is assigned to Cesar

2024-02-01 23:35 UTC, LinconOssa commented on src/pages/people/outlets/palette/form/RenderContentFormNeutralPalette/index.tsx
> +import { useState } from "react";
Same here

2024-02-02 19:51 UTC, cmarin001 commented on src/components/cards/TokenColorCard/styles.ts
> +      theme?.color?.hover || inube.color.hover};
This line of code is not performing any function

2024-02-04 15:06 UTC, LinconOssa commented on src/components/cards/TokenColorCard/styles.ts
> +      theme?.color?.hover || inube.color.hover};
![image](https://github.com/selsa-inube/isetting/assets/103295353/56d79218-393c-49e6-ac38-300c236fb744)
the code is eliminated and simplified

2024-02-05 19:08 UTC, cmarin001 approved these changes
meet the requirements

2024-02-05 19:09 UTC, merged