Adjust the `<TokenColorCard/>` Component for Independence and Dependency Optimization
selsa-inube/isetting pull request #587
Opened 2024-02-05 22:31 UTC by cmarin001

This pull request addresses necessary adjustments to the `<TokenColorCard/>` component, focusing on improving its independence from other components and optimizing dependency management. The objective is to enhance the component's modularity, performance, and ease of integration within the application.

2024-02-06 12:43 UTC, carin91 requested changes

2024-02-06 12:43 UTC, carin91 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +import { StoryFn } from "@storybook/react";
The RenderCategoryGrid is broken into the storybook.

![image](https://github.com/selsa-inube/isetting/assets/123512032/0574247b-f330-4605-aa0e-86033ad6c265)

2024-02-06 12:43 UTC, carin91 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +  type: "colorPicker",
The type control it is not a string, is typeOf ["colorPicker", "tokenPicker"].

![image](https://github.com/selsa-inube/isetting/assets/123512032/9b48d6fb-642c-475c-ac9d-1e80d2a67dce)

2024-02-06 12:43 UTC, carin91 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +  templateRows: "repeat(10, 1fr)",
I would refactor this interface. As you can see in the code, the renderCategoryGrid is using the useMediaQuery hook, as its parents, are the templateRows / templateColumns props or should be calculated inside the renderCategoryGrid?

Comparing it to the design-system i can understand this way of thinking, considering that the design-system consider the column and row templates as props. However, do you think it is the best way to do that?
![image](https://github.com/selsa-inube/isetting/assets/123512032/48d933aa-fd36-4b05-aee7-256234c08151)

It will be too much for the renderCategoryGrid to include this calculation? Should exist an additional parent (renderCategoryGrid container) which send this information to renderCategoryGrid.

I'm worried about the responsability, cause i can find some width, templates and so on calculations inside the tokenColorCard, inside the renderCategoryGrid and inside the Palette interface, so, i think that it is not clear who is responsible for it.

I would list the responsibilities to understand who controls which and distribute responsibilities between renderCategoryGrid and its parents.

2024-02-06 12:43 UTC, carin91 commented on src/components/layout/RenderCategoryGrid/index.tsx
> +              <div key={tokenName} onClick={() => onChange(tokenName)}>
is it not mandatory to used styled components? i think this is the first time i have noticed a direct div in iSetting.

2024-02-06 12:43 UTC, carin91 commented on src/pages/people/outlets/palette/form/RenderContentFormPalette/interface.tsx
> +            templateRows="repeat(7, 1fr)"
The only difference between RenderContentFormNeutralPalette and RenderContentFormPalette is the templateRows and templateColumns, however, there are defined 2 different components. This could be a prop pass by palette/interface or this could be control based on the amount of categories. Either way, this should be refactor using just 1 component. They are exactly the same, line by line.

2024-02-07 21:21 UTC, cmarin001 commented on src/pages/people/outlets/palette/form/RenderContentFormPalette/interface.tsx
> +            templateRows="repeat(7, 1fr)"
solved

2024-02-07 21:30 UTC, cmarin001 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +  templateRows: "repeat(10, 1fr)",
I appreciate your concerns; however, given that our design system is structured in this manner, spreading numerous components throughout the app to attain a singular behavior seems inefficient. While it's true that we're dealing with numerous properties, this is a necessity because the <Grid/> component demands it. Even when we divide responsibilities, we must eventually manage these properties to cater to specific cases.

2024-02-07 21:38 UTC, cmarin001 commented on src/components/layout/RenderCategoryGrid/index.tsx
> +              <div key={tokenName} onClick={() => onChange(tokenName)}>
solved

2024-02-07 22:39 UTC, cmarin001 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +  type: "colorPicker",
solved

2024-02-07 22:39 UTC, cmarin001 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +import { StoryFn } from "@storybook/react";
solved

2024-02-09 00:40 UTC, carin91 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +import { StoryFn } from "@storybook/react";
Not attended:
The storybook presented several problems with some cases.

Check this out:
![image](https://github.com/selsa-inube/isetting/assets/123512032/dd54a594-b68b-474c-b7fd-6a5414c7f94c)

It even produces app breaks in some cases:

![image](https://github.com/selsa-inube/isetting/assets/123512032/95f6043a-7d6c-430c-8358-9f80ce1337c3)

2024-02-09 13:44 UTC, cmarin001 commented on src/components/layout/RenderCategoryGrid/RenderCategoryGrid.stories.tsx
> +import { StoryFn } from "@storybook/react";
solved

2024-02-09 13:58 UTC, carin91 approved these changes

2024-02-09 15:53 UTC, merged