Mock surface token tab for <Nav />
selsa-inube/isetting pull request #591
Opened 2024-02-06 15:38 UTC by LinconOssa

the implementation of nav is carried out.
This will be the last branch called lo/id.. since this branch was there before, the next deliveries will be with lo/set..

2024-02-06 19:19 UTC, carin91 requested changes

2024-02-06 19:19 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/RenderContentFormSurfaceNav.stories.tsx
> +const surfaceFormsConfig = {
Why do you redefine this? it could be imported from surface.config.tsx, you are duplicating the information so... in the case that someone change the suface.config.tsx the changes will not be reflected into the storybool.

2024-02-06 19:19 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/interface.tsx
> +                  <FieldsetColorCard
Verify how to manage pixel perfect,

In the current version there are some differences between with the wireframes.

As an example the width of the FielserColorCard is different. This is an error outside this task? should you adjust it to guarantee the match with the wireframes? should you negotiate some different conditions with Leonardo?

The current state of this branch produces this
![image](https://github.com/selsa-inube/isetting/assets/123512032/e807e57a-a1a8-4237-9808-36107e2e5d5d)

On the contrary, the wireframes are defined as follows:
![image](https://github.com/selsa-inube/isetting/assets/123512032/0dc33816-10b2-4444-b085-d9fc2ad56f6b)

2024-02-06 22:12 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +    blanket: RenderContentFormSurfaceBlanket,
This is done thinking about the generality, that is why the default issue is because all the common ones pass through it, however the specific ones require a special call, whether it is done this way (the most efficient that was found) or by doing it through from an if or switch statement.

2024-02-06 22:15 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +  formType: string;
I understand that you are describing a change that cannot be made because previously something was located in "Apparence" and now it was changed to "string", since within the appearance types from "SendingInformationMessage" "nav", "blanket" are not included. ", nor "navLink". It sounds like you're talking about some kind of development or configuration related to the appearance of an application or system.

2024-02-06 22:16 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +  selectedTab: string;
If it is a string according to the entire infrastructure set up

2024-02-06 22:16 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/config/surface.config.tsx
>            icon: <MdHouse />,
is replaced
![image](https://github.com/selsa-inube/isetting/assets/103295353/f5adbd01-1621-4dd9-906d-ef94ba2c1ac8)

2024-02-06 22:18 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/config/surface.config.tsx
>            icon: <MdHouse />,
This is aligned with the tokens and the icon is only visible on the dark text hover. This setting can be done via text.dark.hover as set out in our layout system:
![image](https://github.com/selsa-inube/isetting/assets/103295353/b3677f53-f612-4ec4-b3b7-ec8e1a2ec536)
![image](https://github.com/selsa-inube/isetting/assets/103295353/a3dce4be-ded0-422b-81a7-989fecbaf41c)

2024-02-06 22:19 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/index.tsx
> +import { useState } from "react";
The color and text issue comes from the design-system and the tokens

2024-02-06 22:20 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/index.tsx
> +import { RenderContentFormSurfaceNavUI } from "./interface";
Thanks for the suggestion, although the change you suggest is correct, it is not something that is within the scope of this Pr since as nav is a component that does import from design-system, where the change should really be made is in design-system, it was discussed with Cesar and will create an issue for this.

2024-02-06 22:21 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/index.tsx
> +    appearance: Appearance | string,
ready thanks for the suggestion
![image](https://github.com/selsa-inube/isetting/assets/103295353/cb4286b0-becf-4896-9b38-5bc0c38b969c)

2024-02-06 22:21 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/index.tsx
> +  const { formType, handleSubmit, surfaceConfig, token } = props;
It's done

2024-02-06 22:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/interface.tsx
> +    surfaceConfig[formType as keyof typeof surfaceConfig].status
Due to type issues, when this adjustment is made it breaks.

2024-02-06 22:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/index.tsx
>  } from "../../config/surface.config";
It's done

2024-02-06 22:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
>  import { RenderSurfaceContentForm } from "./form/RenderContentFormSurface";
It's done

2024-02-06 22:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/RenderContentFormSurfaceNav.stories.tsx
> +  formType: {
The change was made

2024-02-07 19:54 UTC, LinconOssa commented
As agreed, this is what happens and an issue would be created if necessary to accommodate this change.

2024-02-07 19:54 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/interface.tsx
> +                  <FieldsetColorCard
As agreed, this is what happens and an issue would be created if necessary to accommodate this change.

2024-02-08 22:28 UTC, carin91 commented on src/pages/people/outlets/surfaces/interface.tsx
> +  formType: string;
Let's explain it!

1) Investigate about typeof and keyof in the typescript documentation: https://www.typescriptlang.org/docs/handbook/2/typeof-types.html
2) Look at this:
If i declare an object with the structure of inube.color.suface like this:

let surfaceApperances = {
  primary: {
    regular: inube.color.palette.yellow.Y400,
    hover: inube.color.palette.yellow.Y300,
    clear: inube.color.palette.yellow.Y50,
    disabled: inube.color.palette.neutral.N20,
  },
  error: {
    regular: inube.color.palette.red.R400,
    hover: inube.color.palette.red.R300,
    clear: inube.color.palette.red.R50,
    disabled: inube.color.palette.neutral.N20,
  },
  warning: {
    regular: inube.color.palette.yellow.Y400,
    hover: inube.color.palette.yellow.Y300,
    clear: inube.color.palette.yellow.Y50,
    disabled: inube.color.palette.neutral.N20,
  },
  success: {
    regular: inube.color.palette.green.G400,
    hover: inube.color.palette.green.G300,
    clear: inube.color.palette.green.G50,
    disabled: inube.color.palette.neutral.N20,
  },
  information: {
    regular: inube.color.palette.blue.B400,
    hover: inube.color.palette.blue.B300,
    clear: inube.color.palette.blue.B50,
    disabled: inube.color.palette.neutral.N20,
  },
  help: {
    regular: inube.color.palette.purple.P400,
    hover: inube.color.palette.purple.P300,
    clear: inube.color.palette.purple.P50,
    disabled: inube.color.palette.neutral.N20,
  },
  nav: {
    regular: inube.color.palette.neutral.N10,
  },
  navLink: {
    regular: inube.color.palette.neutralAlpha.N0A,
    selected: inube.color.palette.neutral.N30,
    hover: inube.color.palette.neutral.N30,
  },
  blanket: {
    regular: inube.color.palette.neutralAlpha.N100A,
  },
  dark: {
    regular: inube.color.palette.neutral.N900,
    hover: inube.color.palette.neutral.N500,
    clear: inube.color.palette.neutral.N30,
    disabled: inube.color.palette.neutral.N20,
  },
  gray: {
    regular: inube.color.palette.neutral.N30,
    hover: inube.color.palette.neutral.N20,
    clear: inube.color.palette.neutral.N10,
    disabled: inube.color.palette.neutral.N20,
  },
  light: {
    regular: inube.color.palette.neutral.N10,
    hover: inube.color.palette.neutral.N0,
    clear: inube.color.palette.neutral.N0,
    disabled: inube.color.palette.neutral.N20,
  },
};

And with it you define a new Type for keyof typeof like this:

export type SurfaceAppearance = keyof typeof surfaceApperances;

You will obtain the next result:

![image](https://github.com/selsa-inube/isetting/assets/123512032/1781b131-d02e-49c0-a757-a32d3518b2f4)

However, this is extremely  expensive to do that, but this give us the chance to understand the behavior of the keyof typeof

It means that you could reduce this code to the next:

![image](https://github.com/selsa-inube/isetting/assets/123512032/b8374f76-0837-4ccf-a982-0eb36d5cd8a1)

With this, you are creating a Type for the different options in Surface.

And..... This is already done in your code:

![image](https://github.com/selsa-inube/isetting/assets/123512032/023d09db-e8ef-4611-86fc-ec1ffb25e783)

This means that you could import this Type for any Surface children and solve the type issue:
![image](https://github.com/selsa-inube/isetting/assets/123512032/2f24b013-7533-474c-8dde-754f18fdf2d4)

I already told you before about this aproximation, check again the previus issues.

2024-02-08 22:32 UTC, carin91 commented on src/pages/people/outlets/surfaces/interface.tsx
> +  selectedTab: string;
Same as line 29.

2024-02-08 22:36 UTC, carin91 commented on src/pages/people/outlets/surfaces/interface.tsx
> +    blanket: RenderContentFormSurfaceBlanket,
Pending, check the Types issues combine with it. Now you are creating an addtional Type to solve it. That's too much. ![image](https://github.com/selsa-inube/isetting/assets/123512032/f4241e45-56fd-49a5-a9ec-a2c80b65f6cd)

2024-02-08 22:47 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/index.tsx
> +    appearance: Appearance | string,
Solve all of the Appearances issues at once.

2024-02-08 22:55 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/RenderContentFormSurfaceNav.stories.tsx
> +  formType: {
Pending:
![image](https://github.com/selsa-inube/isetting/assets/123512032/f9730ad6-52a3-4f59-96b3-ac3322665c3a)

2024-02-09 23:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +  formType: string;
Resolved

2024-02-09 23:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +  selectedTab: string;
Resolved

2024-02-09 23:22 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/interface.tsx
> +    blanket: RenderContentFormSurfaceBlanket,
Resolved

2024-02-09 23:23 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/index.tsx
> +    appearance: Appearance | string,
If it refers to all the Surface issues, this is it, an issue will have to be created for this to fix it on that card as discussed with Cesar

2024-02-09 23:24 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormNav/RenderContentFormSurfaceNav.stories.tsx
> +  formType: {
Resolved

2024-02-13 11:05 UTC, carin91 approved these changes

2024-02-13 17:32 UTC, cmarin001 approved these changes
meet the requirements

2024-02-13 17:33 UTC, merged