Adjust the <Surfaces/> configuration to display two columns instead of three, as specified in the Figma design
selsa-inube/isetting pull request #597
Opened 2024-02-07 23:08 UTC by LinconOssa

Template Columns is fixed with respect to what is in Figma

2024-02-08 23:45 UTC, carin91 requested changes

2024-02-08 23:45 UTC, carin91 commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  const { "(max-width: 744px)": isSmallScreen } = useMediaQueries([
Wrong use for the useMediaQueries which defines at least 2 boolean variables. Change it to useMediaQuery
Be sure to review design-system documentation for the custom hooks.

2024-02-09 00:57 UTC, LinconOssa commented on src/pages/people/outlets/surfaces/form/RenderContentFormSurface/interface.tsx
> +  const { "(max-width: 744px)": isSmallScreen } = useMediaQueries([
change ready
 
![image](https://github.com/selsa-inube/isetting/assets/103295353/c4809258-01db-473a-beaa-ce905dfaf804)

2024-02-09 10:27 UTC, carin91 approved these changes

2024-02-09 16:29 UTC, merged