Adjust the <Strokes/> configuration to display two columns instead of three, as specified in the Figma design
selsa-inube/isetting pull request #598
Opened 2024-02-07 23:09 UTC by LinconOssa

Template Columns is fixed with respect to what is in Figma

2024-02-08 23:46 UTC, carin91 requested changes

2024-02-08 23:46 UTC, carin91 commented on src/pages/people/outlets/strokes/form/RenderStrokesContentForm/interface.tsx
> +  const { "(max-width: 580px)": isSmallScreen } = useMediaQueries([
Wrong use for the useMediaQueries which defines at least 2 boolean variables. Change it to useMediaQuery
Be sure to review design-system documentation for the custom hooks.

2024-02-09 00:57 UTC, LinconOssa commented on src/pages/people/outlets/strokes/form/RenderStrokesContentForm/interface.tsx
> +  const { "(max-width: 580px)": isSmallScreen } = useMediaQueries([
change ready
![image](https://github.com/selsa-inube/isetting/assets/103295353/66831053-cbd9-4e3f-99d2-4e4f78189ef4)

2024-02-09 10:26 UTC, carin91 approved these changes

2024-02-09 16:17 UTC, cmarin001 approved these changes
meet the requirements

2024-02-09 16:17 UTC, merged