Add modal to confirm logout action
selsa-inube/isetting pull request #607
Opened 2024-02-12 22:40 UTC by cmarin001

This pull request introduces a new feature: a modal dialog that prompts users to confirm their logout action. This enhancement aims to improve the user experience by preventing accidental logouts and ensuring users are making deliberate decisions to exit their sessions.

2024-02-13 12:43 UTC, carin91 requested changes

2024-02-13 17:41 UTC, cmarin001 commented on src/components/feedback/LogoutModal/LogoutModal.stories.tsx
> +import { StoryFn } from "@storybook/react";
solved

2024-02-13 17:43 UTC, cmarin001 commented on src/components/feedback/LogoutModal/index.tsx
> +  const isSmallScreen = useMediaQuery("(max-width: 744px)");
solved

2024-02-13 17:44 UTC, cmarin001 commented on src/components/feedback/LogoutModal/index.tsx
> +      <Blanket>
solved

2024-02-13 17:46 UTC, cmarin001 commented on src/components/feedback/LogoutModal/styles.ts
> +  z-index: 3;
solved

2024-02-13 17:47 UTC, cmarin001 commented on src/components/feedback/LogoutModal/styles.ts
> +  max-height: 180px;
solved

2024-02-13 17:48 UTC, cmarin001 commented on src/components/feedback/LogoutModal/styles.ts
> +const StyledBackdropBlanket = styled.div`
What are the benefits of adopting this approach? Moreover, considering that we're employing non-semantic HTML throughout the application, I believe we should maintain consistency

2024-02-13 17:49 UTC, cmarin001 commented on src/components/feedback/LogoutModal/index.tsx
> +              <Link to={logoutPath}>
solved

2024-02-14 08:49 UTC, carin91 approved these changes

2024-02-14 08:49 UTC, carin91 commented on src/components/feedback/LogoutModal/LogoutModal.stories.tsx
> +  title: "feedback/logout",
The correct way would be "components/feedback/logout"

![image](https://github.com/selsa-inube/isetting/assets/123512032/e595206c-8433-488f-9b68-c357aad1b9b1)

2024-02-14 14:02 UTC, cmarin001 commented on src/components/feedback/LogoutModal/LogoutModal.stories.tsx
> +  title: "feedback/logout",
solved

2024-02-14 14:13 UTC, merged