Mock the downloadable document
selsa-inube/isetting pull request #637
Opened 2024-02-21 21:37 UTC by Andresbl123

Based on the service for the tokens, mock a service for the client-server app options. It should be loaded once the user access the privileges breadcrump. Each option will be an object with the keys: CODIGO and NOMBRE, the service should load an array with these options.

2024-02-21 23:21 UTC, LinconOssa approved these changes
The card is approved with an opinion that for future deliveries the way to create the branch is fixed, which is with ad/set.../ and take a good look at what card number we are putting.

2024-02-22 10:50 UTC, carin91 requested changes

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +
I agree with this new structure (mocks/privileges) to separate privileges from people. However, create a new folder "documents" to include the documents mocks as the documents.service.

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +const DocumentsServiceMock = [
Create a new file with DocumentsServiceMock definition.

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +export async function updateDocument(
Delete this function.
The documents.service will not have permission to edit, delete, or post documents.

2024-02-22 10:50 UTC, carin91 commented on src/App.tsx
> +      intializedDocumentsData();
Refactor this. We are going to create several services for documents, client.server.options, web.options, and so on. This means that we will have several initializedMock functions.

To maintain a clean code, create a util that calls all initialized functions and invoke this util in the login.

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +  readonly id: number;
The id is currently being created using uuid in the backend, therefore, typeof(id)=string.

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +      id: document.CODIGO,
For mocks, we are using a randomly created string , the id will be assign with it.

let id = Math.random().toString(36).substring(2, 9);

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +  if (!document) return console.warn("No documents found");
We must avoid any use of the console as in console.log(), console.warn() and console.error().
During you writing process you could any debugging you want, however i could not be in the main branch.
Change this code line to throw an error in the promise response.

2024-02-22 10:50 UTC, carin91 commented on src/App.tsx
> +import { RespondInvitationRoutes } from "./routes/respondInvitation";
Too much responsibilities and imports to the App/ component. 

We must avoid to have too much imports, refactor this as commented in the next comment.

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +export async function intializedDocumentsData() {
This initialized function will be used in several mocks, so, it could be an util with at least 2 props: nameDBToMock and dataDBToMock

2024-02-22 10:50 UTC, carin91 commented on src/mocks/privileges/documents.service.ts
> +  localforage.clear();
With this, every initializedFunction() has a clear method, so, how do you guarantee that one function will not delete the information created with another function?.

Address this issue using the refactor requested in the feedback of the App component

2024-02-22 15:22 UTC, Andresbl123 commented on src/mocks/privileges/documents.service.ts
> +const DocumentsServiceMock = [
resuelto

2024-02-22 15:23 UTC, Andresbl123 commented on src/mocks/privileges/documents.service.ts
> +  readonly id: number;
resuelto

2024-02-22 15:23 UTC, Andresbl123 commented on src/mocks/privileges/documents.service.ts
> +  if (!document) return console.warn("No documents found");
resuelto

2024-02-22 15:36 UTC, Andresbl123 commented on src/App.tsx
> +      intializedDocumentsData();
resuelto

2024-02-23 11:15 UTC, carin91 requested changes

2024-02-23 11:39 UTC, carin91 requested changes

2024-02-23 11:39 UTC, carin91 commented on src/utils/initializeDataDB.ts
> +import localforage from "localforage";
We should hold all of the DB mocking in 1 same place to haste the back-front integration. Therefore, relocate this file/function in a directory inside @mocks.

2024-02-23 16:04 UTC, Andresbl123 commented on src/mocks/privileges/documents/documents.service.ts
> +      const foundData = optionsData.find((data) => data.codigo === code);
resuelto

2024-02-23 16:04 UTC, Andresbl123 commented on src/mocks/privileges/documents/documents.service.ts
> +    }
resuelto

2024-02-23 16:05 UTC, Andresbl123 commented on src/mocks/privileges/documents/documents.service.ts
> +      if (!optionsData || optionsData.length === 0)
resuelto

2024-02-23 16:05 UTC, Andresbl123 commented on src/utils/initializeDataDB.ts
> +import localforage from "localforage";
resuelto

2024-02-23 16:25 UTC, carin91 approved these changes

2024-02-23 16:25 UTC, merged