Including clients options into the storybook
selsa-inube/isetting pull request #638
Opened 2024-02-22 16:24 UTC by LinconOssa

The stories include the ability to select among Corbanca and Fondecom clients. Present and Cooservunal this has the functionality to exchange between the tokens of each clients.

2024-02-23 16:28 UTC, Andresbl123 commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
>              handleSubmit: () => {},
para no dejar esta función vacía podemos utilizar los actinos de Storybook ejem: se importa action
`import { action } from "@storybook/addon-actions";` y aqui hacemos algo como esto: ` handleSubmit: action("handleSubmit"),` cuando se realice el evento, en storybook no lo documenta así : 
![image](https://github.com/selsa-inube/isetting/assets/74839801/22eb0e91-8d8c-4ada-a5d9-f35e5090e7b6)

2024-02-23 16:28 UTC, Andresbl123 commented on src/pages/people/outlets/color/surfaces/stories/Surfaces.stories.tsx
>              handleSubmit: () => {},
Aquí podemos hacer lo mismo en la recomendación dada

2024-02-23 19:55 UTC, LinconOssa commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
>              handleSubmit: () => {},
Resolved
![image](https://github.com/selsa-inube/isetting/assets/103295353/035302b3-78e5-46db-a361-b57c13c70501)

2024-02-23 19:55 UTC, LinconOssa commented on src/pages/people/outlets/color/surfaces/stories/Surfaces.stories.tsx
>              handleSubmit: () => {},
Resolved

2024-02-26 13:02 UTC, carin91 requested changes

2024-02-26 13:02 UTC, carin91 commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
> +            tokenWithRef: tokensWithReference[context.args.formType],
Change the "formType" name for "clientName" or a more appropriate name.

2024-02-26 13:02 UTC, carin91 commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
> +  formType: "presente",
Change the "formType" name for "clientName" or a more appropriate name.

2024-02-26 14:26 UTC, LinconOssa commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
> +  components: Palette,
Resolved

2024-02-26 14:27 UTC, LinconOssa commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
> +      context: { args: { formType: keyof typeof tokensWithReference } }
Resolved
![image](https://github.com/selsa-inube/isetting/assets/103295353/a5a3f5cc-4888-43ba-9f6e-d9bbe1998940)

2024-02-26 14:27 UTC, LinconOssa commented on src/pages/people/outlets/color/palette/stories/Palette.stories.tsx
> +            tokenWithRef: tokensWithReference[context.args.formType],
Resolved
![image](https://github.com/selsa-inube/isetting/assets/103295353/f116c1ea-a1a0-451b-8464-86baee5658e6)

2024-02-26 14:27 UTC, LinconOssa commented on src/pages/people/outlets/color/palette/stories/props.ts
> +  formType: {
Resolved
![image](https://github.com/selsa-inube/isetting/assets/103295353/abb7ac4c-0188-415f-95fd-cde217657de1)

2024-02-27 02:01 UTC, carin91 approved these changes

2024-02-27 02:01 UTC, merged