Fix the type issue in privileges related to the IClient
selsa-inube/isetting pull request #639
Opened 2024-02-23 12:19 UTC by carin91

The IClient type changes during the redefinition of the AppContext. The main change was the type of the id property, from number to string.

This causes several type errors on privileges outlets due to duplicity in the IClient type definition.

This adjustment includes deleting the double IClient definition and changing all of the import routes.

2024-02-23 20:38 UTC, LinconOssa requested changes

2024-02-23 20:38 UTC, LinconOssa commented on src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/interface.tsx
> +                appearance={formType as SurfaceAppearance}
Whether you need SurfaceAppearance or just leave formType?

2024-02-23 20:38 UTC, LinconOssa commented on src/pages/people/outlets/typography/fonts/Fonts.stories.tsx
>    components: [Fonts],
This is necessary [] you can simply put ,components: Fonts,?

2024-02-23 20:38 UTC, LinconOssa commented on src/pages/people/outlets/typography/fonts/form/RenderFormFonts/RenderFormFonts.stories.tsx
>    components: [RenderFormFonts],
Same here

2024-02-23 20:38 UTC, LinconOssa commented on src/pages/people/outlets/typography/fonts/form/RenderFormFonts/RenderFormFonts.stories.tsx
> +          tokenWithRef: presente,
One question here, we would have to make it so that it can only do Present or tokensWithReference[context.args.formType] so that it can select the others as is being done in activity 708 or does it have nothing to do with it here?

2024-02-26 09:50 UTC, carin91 commented on src/pages/people/outlets/color/surfaces/form/RenderContentFormSurface/interface.tsx
> +                appearance={formType as SurfaceAppearance}
This method, called TypeAssertion, is used to inform the compiler of additional information about the input. I guessed i used it for this component due to the previous multiple definitions of the typeof formType that we previously had. You must use it to adjust some Typescript warnings/errors when the type is generic.
Problems with generic types:
https://www.geeksforgeeks.org/explain-type-assertions-in-typescript/
Type assertions explanations
 https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions https://www.geeksforgeeks.org/explain-type-assertions-in-typescript/

Due to the adjustments we made to the typeof formType/appearance i decided to delete the type assertion.

2024-02-26 11:45 UTC, carin91 commented on src/pages/people/outlets/typography/fonts/Fonts.stories.tsx
>    components: [Fonts],
Storybook has default behaviors to speed up its use, one of these behaviors is to automatically create controls from components props. 

You can see this default behavior with the Fieldset storybook:
![image](https://github.com/selsa-inube/isetting/assets/123512032/9054bfcf-f602-4560-9d41-316f26f5f8ae)

However, if you use the square brackets [] you are creating an array with one element, the component, preventing the storybook from creating automatic controls and preventing default behavior.

![image](https://github.com/selsa-inube/isetting/assets/123512032/70a4e846-b56d-4e0b-bd24-70d98cf26279)

As you can see throughout the code, the standard used for most of the components is the definition with square brackets, so, it is better to maintain it to hold a consistent coding style.

2024-02-26 11:49 UTC, carin91 commented on src/pages/people/outlets/typography/fonts/form/RenderFormFonts/RenderFormFonts.stories.tsx
> +          tokenWithRef: presente,
I will create a new card for this activity, to hold the same solution for all of the stories.

2024-02-26 14:07 UTC, LinconOssa approved these changes
meets requirement

2024-02-27 01:57 UTC, merged