Add a new table related to "Linix use cases"
selsa-inube/isetting pull request #641
Opened 2024-02-23 18:00 UTC by LinconOssa

These documents were sent the table that was not included because it was what was agreed upon in the meeting and the change was made so that the PageTitle and Breadcrumbs part was not done by hand.

2024-02-26 14:12 UTC, Andresbl123 commented on src/pages/privileges/outlets/useCases/index.tsx
> +  const handleToggleMenuInvitation = () => {
esta función `handleToggleMenuInvitation` se esta declarando y se pasa como props a `UseCasesUI`, pero allí nunca se usa

2024-02-26 14:12 UTC, Andresbl123 commented on src/pages/privileges/outlets/useCases/index.tsx
> +  const handleCloseMenuInvitation = () => {
esta función `handleCloseMenuInvitation`se esta declarando y se pasa como props a `UseCasesUI`, pero allí nunca se usa

2024-02-26 14:12 UTC, Andresbl123 commented on src/pages/privileges/outlets/useCases/styles.ts
> +const StyledMessageContainer = styled.div`
Este styled comoponent se declara pero no se utiliza en ninguna parte de lo implementado

2024-02-26 14:12 UTC, Andresbl123 commented on src/pages/privileges/outlets/useCases/index.tsx
> +      handleCloseMenuInvitation={handleCloseMenuInvitation}
Quizás el nombre de estas funciones no sean las mas adecuadas ya que estamos hablando del caso de uso de `casos de uso`

2024-02-26 14:12 UTC, Andresbl123 commented on src/pages/privileges/outlets/useCases/index.tsx
> +function UseCases() {
Se esta presentando este warning y creo que es de parte de nosotros (isetting): 
![image](https://github.com/selsa-inube/isetting/assets/74839801/675665d3-1e8b-4a9d-a0f2-bf66086a2dd9)

2024-02-26 21:29 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +      handleCloseMenuInvitation={handleCloseMenuInvitation}
![image](https://github.com/selsa-inube/isetting/assets/103295353/629a21b0-e29a-487d-80d4-b10782c9d477)
I changed it to the following.

2024-02-26 21:29 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +function UseCases() {
I fixed it with this:
![image](https://github.com/selsa-inube/isetting/assets/103295353/bb512cb5-0914-4572-86cf-1f89270debb5)

2024-02-26 21:30 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +  const handleToggleMenuInvitation = () => {
I deleted it because I am not using it at the moment.

2024-02-26 21:30 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +  const handleCloseMenuInvitation = () => {
I deleted it because I am not using it at the moment.

2024-02-26 21:30 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/styles.ts
> +const StyledMessageContainer = styled.div`
I deleted it because I am not using it at the moment.

2024-02-27 20:19 UTC, Andresbl123 approved these changes
Cumple requerimiento

2024-02-28 09:25 UTC, carin91 requested changes

2024-02-28 09:25 UTC, carin91 commented on src/pages/privileges/outlets/useCases/interface.tsx
> +                  name="searchUser"
Change the name and id for the Textfield and use a more appropriate one, as: "searchLinixUseCases"

2024-02-28 09:25 UTC, carin91 commented on src/pages/privileges/outlets/useCases/interface.tsx
> +                    <Icon
Complete this structure with the showMenu conditional rendering.

                    {showMenu && (
                      <Menu
                        options={menuInvitationLinks}
                        handleClose={handleCloseMenuInvitation}
                      />
                    )}

Expected onClick:
![image](https://github.com/selsa-inube/isetting/assets/123512032/ad55e63f-d21e-4417-a786-5ccf8b649962)

Current onClick:
![image](https://github.com/selsa-inube/isetting/assets/123512032/fe7291c0-03e4-4ec8-99f0-13240b80f11e)

2024-02-28 09:25 UTC, carin91 commented on src/pages/privileges/outlets/useCases/interface.tsx
> +          <StyledContainer>
I cannot understand the use of the StyledContainer, i guess this is related to css context, however, which element required it? Why do we need an additional container over the Stack?

2024-02-28 09:25 UTC, carin91 commented on src/routes/privileges.tsx
> +import { UseCases } from "@src/pages/privileges/outlets/useCases";
use the @pages alias

2024-02-28 17:03 UTC, LinconOssa commented on src/pages/privileges/outlets/options/config/privileges.config.tsx
> +    icon: <MdInventory2 />,
It is changed by:
![image](https://github.com/selsa-inube/isetting/assets/103295353/f99bb9bd-ca05-463a-9733-e1ccd9fea1ef)

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/options/config/privileges.config.tsx
> +    label: "Casos de uso",
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/options/config/privileges.config.tsx
> +    description: "Completa la información para agregar el caso de uso",
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +function UseCases() {
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +  const [searchUseCase, setSearchText] = useState("");
![image](https://github.com/selsa-inube/isetting/assets/103295353/96cd0bb3-485b-4bf4-9d4a-d372e3312161)
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +  const [showMenu] = useState(false);
When this can be done, it is implemented in a future activity. For now, this is pending.

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/interface.tsx
> +                  <>
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/interface.tsx
> +    <>
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/interface.tsx
> +                  name="searchUser"
![image](https://github.com/selsa-inube/isetting/assets/103295353/4832b4b4-794b-436a-bbb4-2bd1ad43d225)
Resolved

2024-02-28 17:04 UTC, LinconOssa commented on src/routes/privileges.tsx
> +import { UseCases } from "@src/pages/privileges/outlets/useCases";
Resolved

2024-02-28 22:45 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/interface.tsx
> +                    <Icon
Ready, I would like some advice to accommodate it on a cell phone since it is out of place because it does not have Tabs

2024-02-28 23:02 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/interface.tsx
> +          <StyledContainer>
If it is not doing anything according to what I saw and delete it.

2024-02-28 23:02 UTC, LinconOssa commented on src/pages/privileges/outlets/useCases/index.tsx
> +import { useState } from "react";
Resolved

2024-02-29 10:49 UTC, carin91 approved these changes

2024-02-29 10:53 UTC, merged