Create a `<SummaryPage />` component
selsa-inube/isetting pull request #643
Opened 2024-02-26 22:35 UTC by Andresbl123

The `<SummaryPage />` component is created, which is intended to show the summary of the steps of an assisted.

2024-02-29 14:16 UTC, LinconOssa requested changes

2024-02-29 14:16 UTC, LinconOssa commented on src/components/layout/Divider/Divider.stories.tsx
> +  component: [Divider],
Igual en todos los que tenga así de las dos observaciones .

2024-02-29 14:16 UTC, LinconOssa commented on src/components/data/BoxAttirbute/BoxAttirbute.stories.tsx
> +  component: [BoxAttribute],
Igual aquí quitar[] ya que estamos haciendo el cambio como usted nos comento.

2024-02-29 14:16 UTC, LinconOssa commented on src/components/data/BoxAttirbute/BoxAttirbute.stories.tsx
> +const story = {
Agregar esto ya que se esta haciendo el cambio para todas
const story: Meta<typeof BoxAttribute>

2024-02-29 14:16 UTC, LinconOssa commented on src/components/data/Accordion/stories/Accordion.stories.tsx
> +        attribute: "Nombre del casi de uso",
Es "caso" de uso

2024-02-29 15:50 UTC, Andresbl123 commented on src/components/data/Accordion/stories/Accordion.stories.tsx
> +        attribute: "Nombre del casi de uso",
resuelto

2024-02-29 16:07 UTC, Andresbl123 commented on src/components/layout/Divider/Divider.stories.tsx
> +  component: [Divider],
resuelto

2024-02-29 16:07 UTC, Andresbl123 commented on src/components/data/BoxAttirbute/BoxAttirbute.stories.tsx
> +  component: [BoxAttribute],
resuelto

2024-02-29 16:08 UTC, Andresbl123 commented on src/components/data/BoxAttirbute/BoxAttirbute.stories.tsx
> +const story = {
resuelto

2024-02-29 16:48 UTC, LinconOssa approved these changes
Cumple requerimiento

2024-03-05 12:45 UTC, carin91 requested changes

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/stories/ControllerAccordion.tsx
> +import { MdArrowBack } from "react-icons/md";
This should be a Layout, we need to create several summary pages (users, roles, LinixUseCases), therefore, there should be a component to do that.

I will assign a new card for this component, meanwhile, delete file. Could you reuse some of this code for the component? If so, save it for you.

However, create a Story for the purpose of this task.

![image](https://github.com/selsa-inube/isetting/assets/123512032/9ea951fb-31ab-4d56-92cc-1c1d70fd6c8e)

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/stories/Accordion.stories.tsx
> +const meta: Meta<IAccordionProps> = {
The meta element with a type of Meta requires the component as argument, not the component props. Therefore, this type should be changed considering the type of Accordion

![image](https://github.com/selsa-inube/isetting/assets/123512032/9268b877-3564-4bd8-b3fc-50c91fda9737)

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/stories/Accordion.stories.tsx
> +  title: "data/Accordion",
I would use a different path. In the project folder you placed this component into components/data/Accordion, why do you use a different folder in the storybook? 

![image](https://github.com/selsa-inube/isetting/assets/123512032/f02cd53b-ddb5-4a42-aef9-d45b991ec7c5)

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +export const StyledContainer = styled.div<IStyledContainer>`
Why do you need to create a styled.div, i would use the Stack component from the inube design-system, could you not?

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +  padding: ${({ isMobile }) => (isMobile ? "16px" : "20px")};
We must use the inube.spacing, even with 0, refactor to use the spacing tokens.

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +  display: flex;
This is the default definition for flex-direction, is it not? why do you need to assign the property?

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +  gap: "16px";
We must use the inube.spacing, even with 0, refactor to use the spacing tokens.

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +  min-height: 160px;
This property assignment should be deleted/refactored. It breaks the expected behavior of setIsOpen

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +  min-height: 160px;
![image](https://github.com/selsa-inube/isetting/assets/123512032/c434b6db-c2be-48e4-941d-e0187c355c04)

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +  border: 1px solid
We must use the inube.spacing, even with 0, refactor to use the spacing tokens.

2024-03-05 12:45 UTC, carin91 commented on src/components/data/Accordion/styles.ts
> +export const StyledHead = styled.button`
I strongly disagree with this. Are you using a button as the container of the whole component? Refactor this to use the proper html elements. I strongly suggest to use the Stack component from inube design system

2024-03-05 15:24 UTC, Andresbl123 commented on src/components/layout/Divider/Divider.stories.tsx
> +const meta: Meta<IDividerProps> = {
Resuelto.

Aunque en este caso es lo mismo, ya que lo que hace Storybook es tomar el tipado del componente, que a la final es la `interface` 
![image](https://github.com/selsa-inube/isetting/assets/74839801/f8c8b0b1-84c2-408c-8129-9091281ad6ca)
![image](https://github.com/selsa-inube/isetting/assets/74839801/80bc3b22-5dc0-46ad-90ed-25130aff2486)

2024-03-05 16:29 UTC, Andresbl123 commented on src/components/data/Accordion/styles.ts
> +  border: 1px solid
aquí pienso que no se deben usar los token de espaciado por que a la final están pensado mara las margins,  padding y el gap, no para bordes o definición de tamaños

2024-03-05 16:29 UTC, Andresbl123 commented on src/components/data/Accordion/styles.ts
> +  gap: "16px";
resuelto

2024-03-05 16:29 UTC, Andresbl123 commented on src/components/data/Accordion/styles.ts
> +  display: flex;
No entiendo muy bien, la sugerencia, pero el valor por default de `flex-direction` es `row`, por lo que aquí se cambia a `column`

2024-03-05 16:35 UTC, Andresbl123 commented on src/components/layout/Divider/styles.ts
> +  margin: 0;
para el height, si aplica, para las márgenes, se establece el valor en 0px, ya que si no se crean unas márgenes que afectan el maquetado, que podría ser por la herencia en css

2024-03-05 16:36 UTC, Andresbl123 commented on src/components/layout/Divider/styles.ts
> +  margin: 0;
resuelto

2024-03-05 16:36 UTC, Andresbl123 commented on src/components/layout/Divider/styles.ts
> +  height: 0px;
resuelto

2024-03-05 16:38 UTC, Andresbl123 commented on src/components/data/Accordion/styles.ts
> +  min-height: 160px;
resuelto

2024-03-05 16:54 UTC, Andresbl123 commented on src/components/data/Accordion/styles.ts
> +export const StyledHead = styled.button`
resuelto

2024-03-07 08:53 UTC, carin91 approved these changes

2024-03-07 08:53 UTC, merged