Refactoring forms in complete-invitation
selsa-inube/isetting pull request #652
Opened 2024-02-28 23:07 UTC by Andresbl123

The AidBudgetsForm, the branchesForm, the EventsForm, the PayrollsForm, and the ProjectsForm are the same, they use the AssignmentForm but define different titles, and so on.

Refactor the CompleteInvitation and the AssignmentForm components to delete all of the other forms or create a new generic componentForm if necessary (I think it is not).

2024-03-01 15:20 UTC, LinconOssa approved these changes
It meets the requirements and would be to modify the storybook as discussed to make the new change.

2024-03-05 15:24 UTC, carin91 requested changes

2024-03-05 18:30 UTC, Andresbl123 commented on src/pages/privileges/outlets/users/complete-invitation/index.tsx
> +import { InitialiserForm } from "../edit-user/forms/InitialiserForm";
resuelto

2024-03-05 18:30 UTC, Andresbl123 commented on src/pages/privileges/outlets/users/edit-user/forms/InitialiserForm/InitialiserForm.stories.tsx
> +  components: [InitialiserForm],
resuelto

2024-03-05 18:30 UTC, Andresbl123 commented on src/pages/privileges/outlets/users/edit-user/forms/InitialiserForm/index.tsx
>      readOnly,
resuelto

2024-03-05 18:30 UTC, Andresbl123 commented on src/pages/privileges/outlets/users/edit-user/forms/InitialiserForm/index.tsx
> +  const [aidBudgetUnits, setAidBudgetUnits] = useState(dataOptionsForms);
resuelto

2024-03-06 11:00 UTC, carin91 requested changes

2024-03-06 11:00 UTC, carin91 commented on src/pages/privileges/outlets/users/edit-user/forms/InitializerForm/InitializerForm.stories.tsx
> +  components: [InitializerForm],
This form will be used more than 10 times on our page. The storybook is important for this component. Therefore, complete the storybook considering types, controls, and so on.

2024-03-07 14:30 UTC, Andresbl123 commented on src/pages/privileges/outlets/users/edit-user/forms/InitializerForm/index.tsx
resuelto

2024-03-07 14:30 UTC, Andresbl123 commented on src/pages/privileges/outlets/users/edit-user/forms/InitializerForm/InitializerForm.stories.tsx
> +  components: [InitializerForm],
resuelto

2024-03-07 15:00 UTC, carin91 approved these changes

2024-03-07 15:00 UTC, merged