Create a table in privileges for `Roles`
selsa-inube/isetting pull request #659
Opened 2024-03-06 19:53 UTC by Andresbl123

Create a new “roles” option, including a table. (This information is currently used in the AppMenu Default Story.

2024-03-08 18:06 UTC, LinconOssa approved these changes
Cumple con requerimientos

2024-03-08 19:59 UTC, carin91 requested changes

2024-03-08 19:59 UTC, carin91 commented on src/mocks/privileges/roles/rolesData.muck.ts
> +export const roles = [
Change the name of the file, rolesData.mock.ts

2024-03-08 19:59 UTC, carin91 commented on src/mocks/privileges/roles/rolesData.muck.ts
> +    aplicaicionRoles: "cooservunal",
Adjust the name for this key, aplicationRoles

2024-03-08 19:59 UTC, carin91 commented on src/mocks/privileges/roles/rolesData.muck.ts
> +    id: "11",
Change the example based on this examples:
https://senlinea.sharepoint.com/:x:/s/isetting221/EdnkwzE5dxpCjCDVZqnEPPgByLi_J40olmbVB05AoGn8sw?e=OfbsqY
![image](https://github.com/selsa-inube/isetting/assets/123512032/bc6759bd-d564-4df4-b9e5-d7838965b218)

2024-03-08 19:59 UTC, carin91 commented on src/mocks/privileges/roles/rolesData.muck.ts
> +    code: 1121212,
The backend service contains: (Código, Nombre, Descripción, Aplicación, Estado) and should be able to use "Activar", "Editar" y "Eliminar", Therefore, the id key chould be deleted, 
![image](https://github.com/selsa-inube/isetting/assets/123512032/b110bb4d-f30b-4cf4-8748-809e868100e3)

The keys for this entity are:
![image](https://github.com/selsa-inube/isetting/assets/123512032/ac8d1332-3acc-4ad8-81c5-451e66fdac6c)

So the appropriate mock should be:
  {
    k_rol: 23123213,
    n_rol: "Analista de Crédito",
    n_uso: "Este es un analista de crédito"
    k_aplica : "Viabilizar crédito",
   i_activo: "0",
  },

2024-03-11 09:53 UTC, carin91 approved these changes

2024-03-11 09:57 UTC, merged