create first step general information for roles
selsa-inube/isetting pull request #669
Opened 2024-03-12 03:30 UTC by Andresbl123

implement the first step of the add role assistant, which corresponds to general information

2024-03-12 11:00 UTC, carin91 requested changes

2024-03-12 11:00 UTC, carin91 commented on src/pages/privileges/outlets/roles/assistedRoles/addRole/config/fiststeps/index.tsx
> +import { useState } from "react";
the assisted addRole, the firsstep, index and interface of the addRole mus be relocate in roles/add-role as the linix-use-case tree

![image](https://github.com/selsa-inube/isetting/assets/123512032/b40ff323-7eb7-4470-9dee-19107b903135)

Considering the future implementation of editRole, i would placed the forms in the roles folder outlets/roles/forms/generalInformation, outlets/roles/forms/AuxiliaryAccounts, and so on.

2024-03-12 11:00 UTC, carin91 commented on src/pages/privileges/outlets/roles/assistedRoles/addRole/config/fiststeps/index.tsx
> +    //currentInformation,
This information will be used in the editRole assited form. So, you could hold this definition and check if the assisted is the editRole or createRole

2024-03-12 11:00 UTC, carin91 commented on src/pages/privileges/outlets/roles/assistedRoles/addRole/config/fiststeps/index.tsx
> +  const [formInvalid, setFormInvalid] = useState(false);
I understand that this is the way how the complete-invitation was written. However, this is the best way? it is important to notice that the whole assisted form is 1 form, so, before submitting the whole form the app will need a validation check for the whole form.

I strongly recommend using one of these approaches (1) do not use formik and create just 1 form in the addRole/index or (2) use formik and create just 1 form in the addRole/index.

However, for the steps that need it, you should include a validation, i would pass the formik validation as prop and the validation will be managed into the assistedRole.

2024-03-12 22:37 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/assistedRoles/addRole/config/fiststeps/index.tsx
> +    //currentInformation,
resuelto

2024-03-12 22:37 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/assistedRoles/addRole/config/fiststeps/index.tsx
> +import { useState } from "react";
resuelto

2024-03-13 19:33 UTC, LinconOssa approved these changes
Cumple con requerimientos

2024-03-14 12:13 UTC, carin91 requested changes

2024-03-14 12:13 UTC, carin91 commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +            handleNextStep(currentStep);
This button could be disabled with the isCurrentStateValid prop.

Could you use the form Button? i would refactor this to use the form Button component.

2024-03-14 20:31 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/interface.tsx
> +import { MdOutlineError } from "react-icons/md";
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +import { useState } from "react";
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +import { useFormik } from "formik";
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +  const initialValues: IGeneralInformationFormProps = {
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +  const { withSubmitButtons, handleSubmit, onHasChanges, readOnly } = props;
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +  const handleChangeForm = async (
resuelto

2024-03-14 20:32 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +  const [formInvalid, setFormInvalid] = useState(false);
Resuelto

2024-03-14 20:33 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/interface.tsx
> +import { IGeneralInformationFormProps } from ".";
resuelto

2024-03-14 20:33 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/interface.tsx
> +  "Digita el nombre o numero de identificación.": "",
resuelto

2024-03-14 21:16 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +
resuelto

2024-03-14 21:16 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +
resuelto

2024-03-14 21:27 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/interface.tsx
> +import { privilegeOptionsConfig } from "@pages/privileges/outlets//options/config/privileges.config";
Resuelto

2024-03-14 21:29 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +        <Button disabled>Atras</Button>
Se va dejar como esta por ahora como se dijo en la reunion  luego plantear algo mejor

2024-03-14 21:29 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +            handleNextStep(currentStep);
Se va dejar como esta por ahora como se dijo en la reunion  luego plantear algo mejor

2024-03-14 21:29 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +      formik.handleSubmit();
Según lo que se hablo en la reunion se deja para una actividad futura de validación o cuando lo tengamos mejor planteado por ahora se dejara como esta

2024-03-14 21:29 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/add-role/config/fiststeps/index.tsx
> +    onSubmit: () => {
Según lo que se hablo en la reunion se deja para una actividad futura de validación o cuando lo tengamos mejor planteado por ahora se dejara como estas

2024-03-15 05:24 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/config/dataRoles.tsx
>  const handleActiuve = (id: string) => {
resuelto

2024-03-15 05:24 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +            handleNextStep(currentStep);
corregido, tener en cuenta que por ahora FormButton no cumple del todo las funcionales esperada con el texto esperado, (Aunque el button dice guardar, él  hace el cambio de paso )

2024-03-15 05:24 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +        gap="16px"
resuelto

2024-03-15 05:26 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/add-role/interface.tsx
> +const roleData = roles.map((rol) => ({
resuelto

2024-03-15 06:30 UTC, carin91 approved these changes

2024-03-15 06:30 UTC, merged