Lo/set766/create the first step general information for linix use cases
selsa-inube/isetting pull request #672
Opened 2024-03-12 20:58 UTC by LinconOssa

Assisted step number one is implemented

2024-03-13 14:50 UTC, Andresbl123 approved these changes

2024-03-13 18:10 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/FirstStep/index.tsx
> +  const initialValues: IGeneralInformationFormProps = {
Listo

2024-03-13 19:06 UTC, Andresbl123 approved these changes

2024-03-14 13:03 UTC, carin91 requested changes

2024-03-14 13:03 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +  Button,
hold this import structure:

import from external libraries.

import from internal components with aliases

import from internal components without aliases.

As an example:
![image](https://github.com/selsa-inube/isetting/assets/123512032/eef1bf95-3b88-47ad-b6f7-cc8897f5c625)

2024-03-14 13:03 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +const caseUseLinixData = linixUseCases.map((linixUseCases) => ({
This information is not used in this context, delete the caseUseLinixData considering that you are "creating a new use Case".
However, if you need this information, this should be passed through props from its parent. Remember that this information is given by a DB and fetch in the roles table.

2024-03-14 13:03 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +            <GeneralInformationForm
do not pass the currentInformation for this call. The currentInformation will be pass for the "edit" option of the form, this will be trigger by the "editar" button in the roles table.

![image](https://github.com/selsa-inube/isetting/assets/123512032/2f54c9f6-2f96-4ef8-a9f8-b4ffe90702f8)

2024-03-14 13:03 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +      <Stack justifyContent="flex-end" whith="100%" gap="12px">
Use the inube spacing.

gap ={inube.spacing.s150}

2024-03-14 13:03 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +          Continuar
This is not the information that the next button should contain. Accordingly to the wireframes the correct word is "Siguiente"

2024-03-14 13:03 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +        <Button appearance="primary" type="submit" onClick={onClick}>
This button could be disabled with the isCurrentStateValid prop.

Could you use the form Button? i would refactor this to use the form Button component.

2024-03-15 21:52 UTC, carin91 approved these changes

2024-03-15 21:52 UTC, merged