Refactor `<ActivateUserModal />`
selsa-inube/isetting pull request #674
Opened 2024-03-13 22:25 UTC by Andresbl123

refactor the `<ActivateUserModal /> component (now `<ActivateFormOptions />`) so that it does not depend on the data structure of the form or assisted by `user`, but rather makes this data structure more generic for any form, where by means of `id` & `activate` you can do what you are looking for with the component in a more generic way,

This component must now be passed a generic, for TS help

2024-03-13 22:30 UTC, Andresbl123 commented
Tener en cuenta que por el momento se genera un nuevo error en cuanto a tipado, en el componente `<DecisionModal />`, ya que este tambien va ligado a la estructura de datos de `IGeneralInformationEntry` asaociados al formulario de usuarios, pienso que esto se debe resolver en una nueva PR, para que esta no se vuelve tan grande 
![image](https://github.com/selsa-inube/isetting/assets/74839801/6cd0151c-acf3-4ba0-ae22-93d6ec1fdd0b)

2024-03-16 14:41 UTC, LinconOssa approved these changes
Meets requirements

2024-03-26 12:09 UTC, carin91 requested changes
Verify several changes i made due to the merge of the main branch into this branch.

You should verify and approve these changes / adjust any elements that you considered.

2024-03-27 01:37 UTC, LinconOssa reviewed
It is getting damaged in the fourth step it is getting undefined

2024-03-27 01:37 UTC, LinconOssa commented on src/pages/privileges/outlets/roles/config/dataRoles.tsx
> +      Activo: roleselectd?.i_Activo === "Y" ? "Si" : "No",
I do not agree with working if and we cannot work with Active" : "Inactive"; or a better name

2024-03-27 14:44 UTC, Andresbl123 commented on src/pages/privileges/outlets/roles/config/dataRoles.tsx
> +      Activo: roleselectd?.i_Activo === "Y" ? "Si" : "No",
resuelto

2024-03-27 20:42 UTC, LinconOssa approved these changes
Meets requirements

2024-03-28 07:37 UTC, carin91 approved these changes

2024-03-28 07:37 UTC, merged