Create the second step CS button option for linixUseCases
selsa-inube/isetting pull request #677
Opened 2024-03-16 00:26 UTC by LinconOssa

The second step of the assisted one is done

2024-03-16 10:40 UTC, carin91 requested changes

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +            disableReset={currentStep === 1} // Deshabilita el botón de reset
Don't leave the code commented

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +    initialValues = {
This must be refactor. why do you include a formik with these initial values?
initalValues = { csButtonOption: ""}

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +export interface IClientServerButtonSelectionProps {
Refactor this, you will need to know the value for csButton only. Do you need an interface for just (1) type? i would delete this interface

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +  withSubmitButtons?: boolean;
Delete this, this is not necessary.

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +    withSubmitButtons,
Why is this necessary? delete this input and refactor the component

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +  const [webOptions, setWebOptions] = useState<Record<string, unknown>[]>([]);
Delete this, this component does not need to know about webOptions. Add to it, you need to consider where to locate every DB consumption. the webOptions should be consumed by the steps 1 and 5, so, for the activity of step 5/7 this "web-options" consumption must be relocate to the assisted form "add-linix-use-case"

For this activity, delete this state and its consumption.

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/interface.tsx
> +  if (withSubmitButtons) {
Avoid this, there must be just 1 return.
return(
{withSubmitButtons? <formButtons></formButtons>: <>{Render...}</>}
)

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/interface.tsx
> +            name="Acción Caso de Uso"
Assign the same name as the formik name of this input, csButtonOption

2024-03-16 10:40 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/interface.tsx
> +            type="actionCaseUse"
Adjust this name, to the csButtonOption

2024-03-16 14:37 UTC, LinconOssa commented on src/components/forms/submit/FormButtons/index.tsx
> +      {children && <Stack direction="column">{children}</Stack>}
Ready

2024-03-16 14:37 UTC, LinconOssa commented on src/components/forms/submit/FormButtons/index.tsx
> +            disabled={disableReset || disabledButtons} // Aquí se aplica la deshabilitación del botón de reset
Ready

2024-03-16 14:37 UTC, LinconOssa commented on src/components/forms/submit/FormButtons/index.tsx
> +            disabled={disableReset || disabledButtons} // Aquí se aplica la deshabilitación del botón de reset
Ready

2024-03-16 14:37 UTC, LinconOssa commented on src/components/forms/submit/FormButtons/index.tsx
> +  disableReset?: boolean; // Nuevo prop para deshabilitar el botón de reset
Ready

2024-03-16 14:37 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/interface.tsx
> +          onChange={(event: { target: { value: string } }) => {
Ready good shape

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/interface.tsx
> +            disableReset={currentStep === 1} // Deshabilita el botón de reset
Ready

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +    initialValues = {
Ready

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +export interface IClientServerButtonSelectionProps {
Ready

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +  withSubmitButtons?: boolean;
Ready

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +    withSubmitButtons,
Ready

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/index.tsx
> +  const [webOptions, setWebOptions] = useState<Record<string, unknown>[]>([]);
Ready removed

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/interface.tsx
> +  if (withSubmitButtons) {
ready

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/interface.tsx
> +            name="Acción Caso de Uso"
Ready and I think this is the same as the figma
![image](https://github.com/selsa-inube/isetting/assets/103295353/e1b14f97-9b98-40e5-8f62-7799abe55347)
![image](https://github.com/selsa-inube/isetting/assets/103295353/fd74caa1-f9f7-43cb-aa34-d96e95be961e)

2024-03-16 14:38 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/ClientServerButtonSelection/interface.tsx
> +            type="actionCaseUse"
Ready

2024-03-17 23:09 UTC, carin91 approved these changes

2024-03-17 23:09 UTC, merged