create the tabs for edit linix use case
selsa-inube/isetting pull request #692
Opened 2024-03-22 23:49 UTC by LinconOssa

.The part is done to avoid a Linux use case. The activity is not complete because there are typing errors. It is missing that it saves when editing something in tabs. It is missing that when I click on the edit icon it shows the tap at once, something that it is not doing until for me to click

.In this activity the correction of the details component is done

2024-03-23 10:47 UTC, carin91 requested changes

2024-03-23 10:47 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/DetailsModal/index.tsx
> +            OpcionButtonClienteServidor: useCase?.k_Ncampo || "",
Actually, this is not correct. You should concatenate k_Ncampo and k_Nforma.

![image](https://github.com/selsa-inube/isetting/assets/123512032/3d059559-b837-4bbd-b5cf-c787e1531e2b)

Try this:
OpcionButtonClienteServidor: useCase?.k_Nforma + "-" + useCase?.k_Ncampo || "",

2024-03-23 10:47 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/DetailsModal/index.tsx
> +            OpcionButtonClienteServidor: useCase?.k_Ncampo || "",
Adjust the label to "Opción botón cliente servidor"
![image](https://github.com/selsa-inube/isetting/assets/123512032/d24f53e6-d824-469d-8d25-5b9e35898cc3)

2024-03-23 10:47 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              withSubmitButtons
Good Job,
However, the forms should be adjusted to present a successful / error response to the HTTP request.
![image](https://github.com/selsa-inube/isetting/assets/123512032/13fe7e19-83a4-49ca-9a7f-af7a255434c6)

2024-03-23 10:47 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +          {selectedTab === stepsAddingLinixUseCase.summary.id.toString() && (
The verification page does not apply to this "edit" linix use case form.

![image](https://github.com/selsa-inube/isetting/assets/123512032/194a2f3d-921c-41dd-aecb-4fae1fb25d7a)

2024-03-27 01:39 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/DetailsModal/index.tsx
> +            OpcionButtonClienteServidor: useCase?.k_Ncampo || "",
resolved

2024-03-27 01:40 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +          {selectedTab === stepsAddingLinixUseCase.summary.id.toString() && (
resolved

2024-03-27 01:40 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/DetailsModal/index.tsx
> +            OpcionButtonClienteServidor: useCase?.k_Ncampo || "",
resolved

2024-03-27 19:33 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              withSubmitButtons
resolved

2024-03-27 19:33 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +          {selectedTab === stepsAddingLinixUseCase.summary.id.toString() && (
resolved

2024-04-01 19:34 UTC, Andresbl123 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +                currentInformation as unknown as IGeneralInformation
Este `as unknown` sobra, se puede dejar solo  `as IGeneralInformation`

2024-04-01 19:36 UTC, Andresbl123 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              handleSubmit={handleSubmit as unknown as () => void}
Este as unknown sobra

2024-04-01 20:31 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +} from "../../adding-linix-use-case";
Resolved

2024-04-01 20:31 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +import { editUserTabsConfig } from "../../../users/edit-user/config/editUserTabs.config";
Resolved

2024-04-01 20:31 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +  controlModal: {
Resolved

2024-04-01 20:31 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +                currentInformation as unknown as IGeneralInformation
Resolved

2024-04-01 20:31 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              handleSubmit={handleSubmit as unknown as () => void}
Resolved

2024-04-02 01:25 UTC, carin91 requested changes

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/forms/InitializerForm/index.tsx
> -import { EMessageType } from "@src/types/messages.types";
Delete any modification of the InitilizerForm

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/forms/InitializerForm/interface.tsx
> +import { RenderMessage } from "@src/components/feedback/RenderMessage";
I do not understand that. Why are you changing @components with @src. It is better to use the more specific one "@commponents"

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> -          type: EMessageType.FAILED,
You must hold the standard use of the EMessageType. Verify the use of this in the people components.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> +          setMessage({
Verify the standard use of the EMessageType

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +import { EditUserUI } from "./interface";
Relocate the imports accordingly to the standard.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +import { linixUseCases } from "@src/mocks/privileges/linixUseCases/LinixUseCases.mock";
Use the @mocks alias. Verify all of the aliases to define imports.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +  const [message] = useState<IUsersMessage>({
Do not use useState if you are not using the settter.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +} from "@pages/privileges/outlets/linixUseCase/adding-linix-use-case/index";
Relocate the imports accordingly to the standard.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +        <Stack gap="32px" direction="column">
adjust the gap value to use the inube spacing.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              csOptions={clientServerMock}
The csOptions should be loaded from the backend services.

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              webOptions={webOptionsMock}
The webOptions should be loaded from the backend services

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              csSelected={""}
This is not ok, should be loaded dfrom the info in the linixUseCase

2024-04-02 01:25 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +            <InitializerForm
All of the initilizer forms should be loaded with the information if the linix Use Case to edit

2024-04-03 20:18 UTC, LinconOssa commented on src/pages/privileges/outlets/forms/InitializerForm/config/messages.config.tsx
> +    description: "Hemos guardado los cambios correctamente para el caso de uso",
Resolved

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/forms/InitializerForm/index.tsx
> +        data: generalMessage.success,
removed it remains the same as it was before

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/forms/InitializerForm/index.tsx
> -import { EMessageType } from "@src/types/messages.types";
removed it remains the same as it was before s

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +import { EditUserUI } from "./interface";
Resolved

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +import { linixUseCases } from "@src/mocks/privileges/linixUseCases/LinixUseCases.mock";
Resolved

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/index.tsx
> +  const [message] = useState<IUsersMessage>({
Resolved

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +} from "@pages/privileges/outlets/linixUseCase/adding-linix-use-case/index";
Resolved

2024-04-03 20:19 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +        <Stack gap="32px" direction="column">
Resolved

2024-04-04 21:47 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> +          setMessage({
A separate card is going to be created to solve the render message so that it works everywhere for now I'm going to leave it like this while we fix it so as not to do double work

2024-04-04 21:47 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> -          type: EMessageType.FAILED,
A separate card is going to be created to solve the render message so that it works everywhere for now I'm going to leave it like this while we fix it so as not to do double work

2024-04-04 21:47 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              csOptions={clientServerMock}
Resolved

2024-04-04 21:47 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +              webOptions={webOptionsMock}
Resolved

2024-04-04 21:47 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/components/EditModal/interface.tsx
> +            <InitializerForm
Resolved

2024-04-05 10:34 UTC, carin91 approved these changes

2024-04-05 10:34 UTC, merged