Mock a DB service for "Acción" in add linix use cases
selsa-inube/isetting pull request #712
Opened 2024-04-05 18:40 UTC by luisalejandrosalazar

2024-04-05 23:19 UTC, LinconOssa commented on src/mocks/utils/initializeDataDB.ts
>  import { webOptionsMock } from "@src/mocks/privileges/web/webOptionsMock.mock";
here you could use the alias @mocks as in the others.

2024-04-06 02:24 UTC, luisalejandrosalazar commented on src/mocks/utils/initializeDataDB.ts
>  import { webOptionsMock } from "@src/mocks/privileges/web/webOptionsMock.mock";
I already added an alias on line 11, isn't that correct?

2024-04-06 02:54 UTC, LinconOssa approved these changes
Meets requirements

2024-04-08 09:40 UTC, carin91 requested changes

2024-04-08 09:40 UTC, carin91 commented on src/pages/privileges/outlets/roles/types.ts
> +export interface IActions {
The actions are related to "Caso de uso linix", therefore, the IActions are a "linix use case" type. Relocate the interface IActions definition to linixUseCase/types.ts

2024-04-08 13:19 UTC, luisalejandrosalazar commented on src/pages/privileges/outlets/roles/types.ts
> +export interface IActions {
Relocated

2024-04-09 09:10 UTC, carin91 approved these changes

2024-04-09 09:10 UTC, merged