create details modal of the positions table
selsa-inube/isetting pull request #723
Opened 2024-04-11 21:07 UTC by ANGIECATHERINEP

create details modal of the positions table

2024-04-11 21:18 UTC, ANGIECATHERINEP commented
The error that is appearing in the Details Modal component (about the lack of selectedItem property) was adjusted by Lincon in set 794

2024-04-14 14:31 UTC, LinconOssa approved these changes
It happens but remember that in order for us to see the details here we have to wait for card 794 to be accepted to see that everything is fine.

2024-04-15 11:42 UTC, carin91 requested changes

2024-04-15 11:42 UTC, carin91 commented on src/pages/privileges/outlets/positions/components/DetailsModal/index.tsx
> +        <InteractiveModal
The Interactive Component is broken due to interventions for SearchUserCard, a new card was created to solve this issue. After this, you could complete this card.

2024-04-15 11:42 UTC, carin91 commented on src/pages/privileges/outlets/positions/config/dataPositions.tsx
> +  const data = [mockRoles.find((role) => role.k_Rol === k_Rol)!].map(
It is much better to solve the roles vs positions issue before everything. Solve first this card, to complete the Details Modal card.

2024-04-19 11:14 UTC, carin91 requested changes

2024-04-19 11:14 UTC, carin91 commented on src/pages/privileges/outlets/positions/config/dataPositions.tsx
> +    MockPositions.find((position) => position.k_Grupo === k_Grupo)!,
You must look into the positions database, not the mockPositions object. Refactor to find in the "linix-positions" mock.

2024-04-20 01:20 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/positions/config/dataPositions.tsx
> +    MockPositions.find((position) => position.k_Grupo === k_Grupo)!,
resolved

2024-04-20 22:29 UTC, carin91 approved these changes

2024-04-20 22:29 UTC, merged