Include validation and next/previous control in adding linix use case
selsa-inube/isetting pull request #730
Opened 2024-04-17 21:09 UTC by LinconOssa

The validation is done for the steps, the buttons are arranged so that they are disabled, there is a missing validation issue for the search that I could not do, I hope for changes to be made since this branch is very large and I think things are missing

2024-04-18 17:02 UTC, luisalejandrosalazar commented
I find that the verification in the required fields is carried out as expected, except in the "Información General" tab, "Opción web" and  "Opción cliente servidor" fields, which Lincon expresses in the previous comment.

2024-04-19 11:57 UTC, carin91 requested changes

2024-04-19 11:57 UTC, carin91 commented on src/components/cards/SearchUserCard/index.tsx
> -          required={true}
There must be a way to control if required or not, therefore, the searchUserCard must include this prop as optional with requiered=false as default value.

2024-04-19 11:57 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> -      initialValues = {
why do you need to delete the default value?

2024-04-19 11:57 UTC, carin91 commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> +      handleSubmit,
Why  is not optional?, how could you control this in the case of adding linix use cases?

2024-04-19 17:55 UTC, LinconOssa commented on src/components/cards/SearchUserCard/index.tsx
> -          required={true}
Resolved

2024-04-19 17:55 UTC, LinconOssa commented on src/pages/privileges/outlets/linixUseCase/adding-linix-use-case/forms/GeneralInformationForm/index.tsx
> +      handleSubmit,
I do not consider it optional since this form is used to add and edit

2024-04-20 22:32 UTC, carin91 approved these changes

2024-04-20 22:32 UTC, merged