json calculator for add positon request
selsa-inube/isetting pull request #745
Opened 2024-04-23 13:47 UTC by ANGIECATHERINEP

json calculator for add positon request

2024-04-23 19:31 UTC, LinconOssa approved these changes
Meets the requirements.

2024-04-24 09:30 UTC, carin91 requested changes

2024-04-24 09:30 UTC, carin91 commented on src/pages/privileges/outlets/positions/add-position/interface.tsx
> +            onClick={
refactor this for better readability. Include the currentStep === steps.length verification into the handleNextStep to call the saveLinixPositions

2024-04-24 09:30 UTC, carin91 commented on src/pages/privileges/outlets/positions/add-position/types.ts
> +  roles: React.RefObject<FormikProps<IOptionInitialiceEntry[]>>;
Is the RefObject necessary? i guess we already delete it from types.ts file on the last review.

2024-04-24 14:12 UTC, merged