Create edit in positions
selsa-inube/isetting pull request #757
Opened 2024-04-26 16:55 UTC by ANGIECATHERINEP

Create edit in positions

2024-04-26 21:26 UTC, luisalejandrosalazar approved these changes
Meets the requirements.

2024-05-04 00:58 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/forms/InitializerForm/index.tsx
> +  editItemData?: (props: functionById) => Promise<unknown>;
What happens is that the functionById interface such as the edit and delete functions are located in src\mocks\utils\dataMock.service.ts

2024-05-04 00:58 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/positions/add-position/forms/GeneralInformationForm/index.tsx
> +    const disabledButtons = (valueCompare: IGeneralInformationEntry) =>
Yes sir, the form works correctly

2024-05-04 00:58 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/positions/add-position/forms/GeneralInformationForm/interface.tsx
> +    return (
resolved

2024-05-06 21:56 UTC, carin91 commented on src/pages/privileges/outlets/forms/InitializerForm/index.tsx
> +  editItemData?: (props: functionById) => Promise<unknown>;
Pending

2024-05-06 22:02 UTC, carin91 commented on src/pages/privileges/outlets/positions/add-position/forms/GeneralInformationForm/interface.tsx
> +  return <>{RenderFormFields(formik, handleChangeForm)}</>;
Pending.

You are passing a react component as a function, therefore, you are not giving the chance to react to calculate which component to rerender or not.

read:
https://react.dev/reference/rules/react-calls-components-and-hooks

2024-05-06 22:03 UTC, carin91 requested changes
Verify that all of the edited files are without warnings / errors.

![image](https://github.com/selsa-inube/isetting/assets/123512032/52dc1af8-807e-42c5-b183-1f8c3d8b3acb)

2024-05-06 23:11 UTC, ANGIECATHERINEP reviewed
additionally adjust the file with errors that you mentioned, but this file is not found in positions

2024-05-07 07:16 UTC, carin91 approved these changes

2024-05-07 07:16 UTC, merged