Create-mock-for-entity-user
selsa-inube/isetting pull request #784
Opened 2024-05-08 23:02 UTC by LinconOssa

The mock is created but there are typing problems and problems in activating and editing that will clear up future tasks that I have already assigned

2024-05-08 23:26 UTC, ANGIECATHERINEP approved these changes
The request was made correctly

2024-05-09 11:20 UTC, carin91 requested changes

2024-05-09 11:20 UTC, carin91 commented on src/pages/privileges/outlets/users/types/forms.types.ts
>  interface IGeneralInformationEntry {
This type should be adjusted, deleting the old definitions as id or userId. If you have any trouble of functionality you must resolve it.

2024-05-09 11:20 UTC, carin91 commented on src/pages/privileges/outlets/users/types/forms.types.ts
> +  k_Usuari: string;
Create a service folder in src/ and locate the interface for the user.

As you can see below, we do this for crediboard:
![image](https://github.com/selsa-inube/isetting/assets/123512032/eeeb80af-dcc4-4b6d-861e-6a5ae57bc72e)

2024-05-09 21:59 UTC, LinconOssa commented on src/pages/privileges/outlets/users/types/forms.types.ts
>  interface IGeneralInformationEntry {
Solved according to what was discussed in other tasks to solve the rest

2024-05-09 21:59 UTC, LinconOssa commented on src/pages/privileges/outlets/users/types/forms.types.ts
> +  k_Usuari: string;
Solved

2024-05-10 19:23 UTC, carin91 requested changes
you must create de "linix-users" mock on the DB

2024-05-14 20:35 UTC, carin91 approved these changes

2024-05-14 20:35 UTC, merged