Adjust invate user accordingly to use-case
selsa-inube/isetting pull request #788
Opened 2024-05-14 21:45 UTC by ANGIECATHERINEP

Adjust invate user accordingly to use-case

2024-05-15 01:46 UTC, LinconOssa approved these changes
It is approved with something missing, which is the date when one believes that we do not know how to solve it so that it is not like this:
![image](https://github.com/selsa-inube/isetting/assets/103295353/b69cee70-ff58-4d63-8bf5-79d7db9858cc)

2024-05-16 11:52 UTC, carin91 requested changes

2024-05-18 00:13 UTC, ANGIECATHERINEP commented on src/components/feedback/InteractiveModal/types.ts
> +    | any;
resolved

2024-05-18 00:13 UTC, ANGIECATHERINEP commented on src/components/feedback/InteractiveModal/types.ts
> +  idLabel: string;
resolved

2024-05-18 00:13 UTC, ANGIECATHERINEP commented on src/pages/privileges/outlets/users/invite/index.tsx
> +import { invitationUserEntriesDataMock } from "@src/mocks/apps/privileges/invitations/invitationUsers.mock";
resolved

2024-05-20 11:08 UTC, merged